/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : number,
  'senderName' : string,
  'message' : string,
}
export interface PlayerState {
  'zPosition' : number,
  'name' : string,
  'isAlive' : boolean,
  'position' : number,
  'health' : number,
}
export interface ScoreEntry {
  'placement' : number,
  'name' : string,
  'kills' : number,
}
export interface _SERVICE {
  'createRoom' : ActorMethod<[string], string>,
  'getChatMessages' : ActorMethod<[string, number], Array<ChatMessage>>,
  'getRoomState' : ActorMethod<[string], Array<PlayerState>>,
  'getTopScores' : ActorMethod<[], Array<ScoreEntry>>,
  'joinRoom' : ActorMethod<[string, string], undefined>,
  'leaveRoom' : ActorMethod<[string, string], undefined>,
  'sendChatMessage' : ActorMethod<[string, string, string], undefined>,
  'submitScore' : ActorMethod<[string, number, number], undefined>,
  'updatePlayerState' : ActorMethod<
    [string, string, number, number, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
